project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/about.qmd
    - pages/methodology.qmd
    - pages/contact.qmd

website:
  title: "Perils"
  navbar:
    logo: assets/logo.svg
    background: light
    left:
      - text: "About"
        href: pages/about.qmd
      - text: "Methodology"
        href: pages/methodology.qmd
      - text: "Contact"
        href: pages/contact.qmd
  page-footer:
    center: |
      &copy; 2026 Perils. All rights reserved.
    right:
      - icon: github
        href: https://github.com/shrutirkashyap/perils

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    grid:
      body-width: 1100px
